# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='カテゴリー')),
            ],
        ),
    ]
