# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='タイトル'),
        ),
    ]
