# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20161126_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, default='category', max_length=255, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(default='url', max_length=255, verbose_name='URL'),
        ),
    ]
